/// Represents a single yoga pose template used for real-time comparison.
///
/// Each template contains:
///   - [name]: Display name of the pose (e.g. "Tree Pose").
///   - [meanVector]: A 24-element normalised vector (12 key joints × [x, y])
///     generated by averaging many labelled images of this pose.
///   - [description]: A short user-facing description of the pose.
///
/// Templates are loaded from `assets/pose_templates.json` at runtime.
/// The [meanVector] is passed to [CosineSimilarityService] as the reference
/// against which the user's live pose is scored.
class PoseTemplate {
  /// Human-readable name shown in the Pose Library list.
  final String name;

  /// The mean normalised pose vector (24 doubles).
  ///
  /// Element layout: [L_Shoulder_x, L_Shoulder_y, R_Shoulder_x, …, R_Ankle_y].
  /// Generated offline by `generate_pose_templates.py`.
  final List<double> meanVector;

  /// Short description displayed under the pose name in the selection UI.
  final String description;

  const PoseTemplate({
    required this.name,
    required this.meanVector,
    required this.description,
  });

  /// Construct a [PoseTemplate] from a decoded JSON map.
  ///
  /// Expected JSON shape:
  /// ```json
  /// {
  ///   "name": "Tree Pose",
  ///   "meanVector": [0.1, -0.5, ...],
  ///   "description": "Stand on one leg …"
  /// }
  /// ```
  factory PoseTemplate.fromJson(Map<String, dynamic> json) {
    return PoseTemplate(
      name: json['name'] as String,
      meanVector: (json['meanVector'] as List<dynamic>)
          .map((e) => (e as num).toDouble())
          .toList(),
      description: json['description'] as String,
    );
  }

  /// Serialise back to a JSON-compatible map (useful for debugging/export).
  Map<String, dynamic> toJson() => {
    'name': name,
    'meanVector': meanVector,
    'description': description,
  };

  @override
  String toString() =>
      'PoseTemplate(name: $name, vector: ${meanVector.length} elements)';
}
